### ISSUE TITLE
index error when loading a CSV file

### ISSUE THREAD

**Issue by dmontagner** [nembery/aframe#1]
### file aframe/endpoints/plugins/FileDiscovery.py

While attempting to load a CSV file, I was getting an error at this part of the code:

```
    def load_instance_config(self, config):
        filename = config["file_path"]["value"]
        try:
```

Python was complaining about the index type that it can't be string and it should be integer.

I did the following modification in order to fix the problem but I don't know if this is the best way to solve. Hence, I am creating this issue instead of doing a pull merge.

The change I applied is this:

```
    def load_instance_config(self, config):
    print "**** HERE ***"
    print(dir(config))
    print "**** HERE ***"
        filename = config[0]["value"]
```

You can ignore the prints as I used them for troubleshooting.

**Comment by nembery** [comment]
yep, looks good. Sorry it took so long to review and apply! thanks for the catch!

 https://github.com/nembery/aframe/commit/da61afa107c75c5ab228bde8068f9ddd37763e90
